apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-module
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main-module
  template:
    metadata:
      labels:
        app: main-module
    spec:
      containers:
        - name: main
          image: muticheck/main-module:latest
          imagePullPolicy: Never
          command: [ "/bin/sh", "-c" ]
          args:
              - |
                if [ -z "$CUSTOM_ARGS" ]; then
                  echo "目前不支持交互式模式"  # 目前不支持进入交互式模式
                else
                  exec /app/muticheck $CUSTOM_ARGS  # 传入参数执行任务
                fi
          env:
            - name: CUSTOM_ARGS
              value: "-"  # 默认不传参数，进入交互模式
        # 默认不传参数，进入交互模式，也可以通过kubectl set env传递参数

