apiVersion: apps/v1
kind: Deployment
metadata:
  name: pocscan-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pocscan
  template:
    metadata:
      labels:
        app: pocscan
    spec:
      containers:
        - name: pocscan
          image: multicheck/pocscan:latest
          # 这里指定镜像为本地镜像
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: output-volume
              mountPath: /app/output/  # 挂载到容器的 output 目录
      volumes:
        - name: output-volume
          persistentVolumeClaim:
            claimName: pocscan-pvc  # 通过 PVC 挂载到容器内
---
apiVersion: v1
kind: Service
metadata:
  name: pocscan-service
spec:
  selector:
    app: pocscan
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080
  type: ClusterIP
