apiVersion: v1
kind: PersistentVolume
metadata:
  name: pocscan-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany  # 根据需要选择 ReadWriteMany 或 ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data1 # 物理机上共享文件的路径
    type: Directory
